version: "3.8"

services:
  wardrove:
    build: .
    container_name: wardrove
    ports:
      - "8847:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Indian/Reunion
